[project]
name = "sqladmin-litestar-plugin"
version = "0.2.0"
description = ""
readme = "README.md"
authors = [
    { name = "Peter Schutt", email = "peter.github@proton.me" },
]
requires-python = ">=3.9"
dependencies = [
    "litestar",
    "sqladmin",
    "typing-extensions",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.codespell]
skip = "poetry.lock,.git.,.idea,.mypy_cache,.venv"

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "if TYPE_CHECKING",
    "pragma: no cover",
    "if __name__ == \"__main__\":",
    "@overload",
    "raise NotImplementedError",
]

[tool.coverage.run]
branch = true
omit = [
    "tests/*",
]
source = [
    "sqladmin_litestar_plugin",
]


[tool.pytest.ini_options]
addopts = [
    "-ra",
    "--strict-config",
]
testpaths = [
    "tests/",
]

[tool.ruff]
line-length = 100
preview = true
src = [
    "src",
    "tests",
]
target-version = "py39"

[tool.ruff.lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FIX",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PERF",
    "PGH",
    "PIE",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PT",
    "PTH",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TD",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
]
ignore = [
    "A003",
    "D100",
    "D101",
    "D104",
    "D105",
    "D102",
    "D103",
    "D106",
    "D107",
    "D203",
    "D213",
    "E501",
    "ISC001",
    "UP040",
    "RUF067",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
]

[tool.ruff.lint.isort]
known-first-party = [
    "sqladmin_litestar_plugin",
    "tests",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.*" = [
    "D",
    "FURB189",
    "S",
    "DTZ001",
]

[dependency-groups]
dev = [
    "advanced-alchemy",
    "anyio",
    "codespell",
    "coverage",
    "mypy",
    "pyright",
    "pytest",
    "pytest-mock",
    "ruff",
    "sqlalchemy",
    "starlette",
    "types-wtforms",
]
examples = [
    "aiosqlite",
    "uvicorn",
]
